version: 2
jobs:

  deploy:
    docker:
      - image: angulito/aws-cli-docker:1.16.86
    steps:

      - checkout

      - run:
          name: Deploy to S3
          command: |
            aws s3 sync . s3://madrid-no-duerme-datathon  --exclude ".*/*" --exclude ".*"

workflows:
  version: 2

  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master